### ISSUE TITLE
global install

### ISSUE THREAD

**Issue by azat-co** [bevacqua/node-emoji-random#1]
This will be more useful as a global CLI tool, right?

**Comment by bevacqua** [comment]
Care to contribute that?

**Comment by azat-co** [comment]
@bevacqua can't promise that it'll be anytime soon ;-) need to finish mongoui first

**Comment by azat-co** [comment]
@bevacqua done sir.

**Comment by bevacqua** [comment]
great, bumped to 0.1.1

**Comment by azat-co** [comment]
@bevacqua forgot the readme.md

it's just -g and then emoji-random

**Comment by bevacqua** [comment]
Updated readme ;)
